project_id = "wwcdntjnpoaacarmmzir"

[functions.create-order]
verify_jwt = true

[functions.create-product]
verify_jwt = true

[functions.delete-product]
verify_jwt = true

[functions.get-inventory]
verify_jwt = true

[functions.get-product-details]
verify_jwt = true

[functions.get-product-form-data]
verify_jwt = true

[functions.get-products-list]
verify_jwt = true

[functions.get-sales-form-data]
verify_jwt = true

[functions.update-product]
verify_jwt = true

[functions.update-stock]
verify_jwt = true

[functions.validate-product-type-change]
verify_jwt = true

[functions.get-shipping-methods]
verify_jwt = true

[functions.create-shipping-method]
verify_jwt = true

[functions.get-shipping-zones]
verify_jwt = true

[functions.cancel-expired-reservations]
verify_jwt = false

[functions.get-terms]
verify_jwt = true

[functions.document-lookup]
verify_jwt = false

[functions.get-sale-products]
verify_jwt = true

[functions.update-order]
verify_jwt = true

[functions.update-order-situation]
verify_jwt = true